### ISSUE TITLE
Prop to pass amount of photos that are not showing

### ISSUE THREAD

**Issue by lucasbento** [duyluonglc/react-native-thumbnail-grid#6]
Hey @duyluonglc, awesome job on this library, I was wondering if there's a way to pass the amount of images that _can be shown_  through a prop instead of passing all the URLs and, if there isn't, is this feature valuable to the library?

My use-case is that I will retrieve 6 images of 20 images from my API and I need to show `+14` on the count.

**Comment by lucasbento** [comment]
Already did a small change for it here: https://github.com/lucasbento/react-native-photo-grid/commit/829f31b969448bfea82b4822f44637c80aa3492e.

**Comment by duyluonglc** [comment]
Hi @lucasbento welcome your PR :)
Should set `PhotoGrid.defaultProps = { numberImagesToShow: 5 }` then replace constant `5` by `numberImagesToShow`

**Comment by lucasbento** [comment]
@duyluonglc: what do you mean? let's continue the review on #7.
